### ISSUE TITLE
Add more descriptive description

### ISSUE THREAD

**Issue by davelab6** [alif-type/reem-kufi#4]
Please add a more descriptive description to the README that describes the design and project in more detail :)

**Comment by khaledhosny** [comment]
It looks descriptive to me, it even has two Wikipedia links :) OK what kind of details you think are missing?

**Comment by davelab6** [comment]
Fair enough :) I was thinking more about particular glyphs of interest, other similar designs you took inspiration from, etc

**Comment by davelab6** [comment]
I was thinking more about particular glyphs of interest, other similar designs you took inspiration from, etc

**Comment by khaledhosny** [comment]
The main source of inspirations are mentioned, there are no other sources as it is a style rarely made into typefaces (all those Kufi typefaces are either faux Kufi or square Kufi, a completely different genre).

**Comment by davelab6** [comment]
:)

**Comment by khaledhosny** [comment]
OK, what about this:

# Reem Kufi

Reem Kufi is a Fatimid-style decorative [Kufic](https://en.wikipedia.org/wiki/Kufic) typeface as seen in the
historical mosques of Cairo, and is largely is based on the Kufic designs of
the late master of Arabic calligraphy [Mohammed Abdul Qadir](https://ar.wikipedia.org/wiki/%D9%85%D8%AD%D9%85%D8%AF_%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%82%D8%A7%D8%AF%D8%B1_%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%84%D9%87_%28%D8%AE%D8%B7%D8%A7%D8%B7%29) who revived
this art in the 20th century and formalised its rules.

Reem Kufi is particularly suitable for display settings, in titles or
decorations. Due to its unmistakable old Kufic style, it gives a feeling of
something old, historical, or Islamic.

Some glyphs in Reem Kufi has several alternate variants that can work better
for different situations, they can be accessed with “Character Variant”
features (`cv01`, `cv02`, and so on). 

Reem is an Arabic female name that literally means “a white deer” and it so
happens to be the name of my daughter.
